// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApEypp98ejnqNxQTCGBXnxEjjZfqYmrMo',
    appId: '1:162225868986:web:fe720d901c34dcf35b3283',
    messagingSenderId: '162225868986',
    projectId: 'agriaid-dd5a2',
    authDomain: 'agriaid-dd5a2.firebaseapp.com',
    storageBucket: 'agriaid-dd5a2.firebasestorage.app',
    measurementId: 'G-S13CQH1PG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjknwFGgA75girWok-X-UlCBL16t0ldBc',
    appId: '1:162225868986:android:116151253dad6fe05b3283',
    messagingSenderId: '162225868986',
    projectId: 'agriaid-dd5a2',
    storageBucket: 'agriaid-dd5a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCHT4Y4AC4-EkQnaofNmIIiXF3vPjr2as',
    appId: '1:162225868986:ios:2085f2c6205721ea5b3283',
    messagingSenderId: '162225868986',
    projectId: 'agriaid-dd5a2',
    storageBucket: 'agriaid-dd5a2.firebasestorage.app',
    iosBundleId: 'com.example.agriaid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCHT4Y4AC4-EkQnaofNmIIiXF3vPjr2as',
    appId: '1:162225868986:ios:2085f2c6205721ea5b3283',
    messagingSenderId: '162225868986',
    projectId: 'agriaid-dd5a2',
    storageBucket: 'agriaid-dd5a2.firebasestorage.app',
    iosBundleId: 'com.example.agriaid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApEypp98ejnqNxQTCGBXnxEjjZfqYmrMo',
    appId: '1:162225868986:web:24a97f17bf27ecee5b3283',
    messagingSenderId: '162225868986',
    projectId: 'agriaid-dd5a2',
    authDomain: 'agriaid-dd5a2.firebaseapp.com',
    storageBucket: 'agriaid-dd5a2.firebasestorage.app',
    measurementId: 'G-RHWD4NSRMD',
  );
}
